### ISSUE TITLE
An error occurred while writing to logger(s). (One or more errors occurred. (A task was canceled.))

### ISSUE THREAD

**Issue by fjmorel** [elmahio/Elmah.Io.Extensions.Logging#4] opened 2019-05-03 14:56 UTC
This morning, logging to Elmah using this package suddenly started failing a lot in one of our services. We have code that sometimes generates a warning, and that failed to log. One of those failures eventually successfully logged to Elmah. This is an ASP.Net Core 2.2 web api.

The service had been running 30 hours when the problem started. When I restarted it, logging to Elmah went back to normal. This was at 9:30 EDT today (May 5, 2019).

```
URL: ~internal data~
Hostname: ~internal data~
Status Code: 500
Type: TaskCanceledException
Message: An error occurred while writing to logger(s). (One or more errors occurred. (A task was canceled.))
Source: null
User: null
Time: 2019-05-03T14:15:19Z
Detail:
System.AggregateException: An error occurred while writing to logger(s). (One or more errors occurred. (A task was canceled.)) ---> System.AggregateException: One or more errors occurred. (A task was canceled.) ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Elmah.Io.Client.Messages.<>c__DisplayClass34_0.<MessagesCreated>b__0(Task`1 a)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Elmah.Io.Client.Messages.CreateAndNotify(Guid logId, CreateMessage message)
   at Elmah.Io.Extensions.Logging.ElmahIoLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger`1.Microsoft.Extensions.Logging.ILogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, Exception exception, String message, Object[] args)
~internal code using ILogger~
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. (A task was canceled.) ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Elmah.Io.Client.Messages.<>c__DisplayClass34_0.<MessagesCreated>b__0(Task`1 a)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Elmah.Io.Client.Messages.CreateAndNotify(Guid logId, CreateMessage message)
   at Elmah.Io.Extensions.Logging.ElmahIoLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---
<---
```

**Comment by ThomasArdal** [comment] 2019-05-03 15:04
That's a good question. It looks like the call to the API fails for some reason, but the stack trace doesn't really reveal why. There was a huge breakdown on all Azure regions previously. It might have had something to do with that. It's strange though, since I haven't heard about logging problems from other users.

Maybe monitor this and get back to me if you experience the same issue again? Sorry that I cannot be of more help, but I suspect this to be caused by the breakdown on Azure.

**Comment by fjmorel** [comment] 2019-05-03 15:22
Ok. It's not first time I've seen it, but I'll keep tracking.

I saw that there's also a `Elmah.Io.AspNetCore` package, and there's a recently merged PR to move the sending of messages to a background queue. Would that helped our API requests not fail when logging failed?

**Comment by ThomasArdal** [comment] 2019-05-03 15:34
It depends on what caused the error in the first place. There is indeed some challenges, if your API starts logging **A LOT** of messages to elmah.io, since that will slow down the request. But it doesn't sound like that was your issue, but rather the logging calls to the elmah.io API that failed.

It's correct that `Elmah.Io.AspNetCore` has been updated to queue up messages before sending them to the API. It's to avoid the problem described above. We want to do the same for `Elmah.Io.Extensions.Logging` eventually, but we are still planning how to solve this best. The issue here is that `Microsoft.Extensions.Logging` and `Elmah.Io.Extensions.Logging` isn't dependent of ASP.NET Core in any way, why we don't have access to the same feature set. The best solution will probably be to built this into the `Elmah.Io.Client` package somehow, which would allow for queued messages in all of the remaining integrations (like Serilog, NLog and log4net).

**Comment by fjmorel** [comment] 2019-05-03 15:38
I understand. Glad to hear it's being worked on! I will probably work on switching to `Elmah.Io.AspNetCore` in the meantime.

**Comment by ThomasArdal** [comment] 2019-05-03 16:00
They are two different packages for two different purposes. If you are looking to log warnings and errors when endpoints fail, `Elmah.Io.AspNetCore` is definitely a better option. Supports manual logging too, which you probably already know. But if you need logging-framework-kind-of-logging, you'd still need `Elmah.Io.Extensions.Logging` :smile:

**Comment by ThomasArdal** [comment] 2019-12-13 18:38
Closing this one since logging has been moved behind a message queue 👍

**Closed as completed by ThomasArdal** 2019-12-13 18:38 UTC
